export const ACTION_TYPES = {
	SHUFFLE: "SHUFFLE",
	DEAL: "DEAL",
	DECLARE_TURUP: "DECLARE_TURUP",
	PICKUP_TURUP_CARD: "PICKUP_TURUP_CARD",
	PLAY_CARD: "PLAY_CARD",
	PLAY_GHOPTE: "PLAY_GHOPTE",
} as const;
