export const ACTION_TYPES = {
	DEAL_FOUR_PLAYER: "DEAL_FOUR_PLAYER",
	DEAL_TWO_PLAYER_HANDS: "DEAL_TWO_PLAYER_HANDS",
	DEAL_TWO_PLAYER_STACKS: "DEAL_TWO_PLAYER_STACKS",
	DECLARE_TURUP: "DECLARE_TURUP",
	PICKUP_TURUP_CARD: "PICKUP_TURUP_CARD",
	PLAY_CARD: "PLAY_CARD",
	PLAY_GHOPTE: "PLAY_GHOPTE",
} as const;
