export const ENGINE_ERROR_CODES = {
	// game creation / configuration
	INVALID_GAME_ID: "INVALID_GAME_ID",
	INVALID_MODE: "INVALID_MODE",
	INVALID_PLAYER_COUNT: "INVALID_PLAYER_COUNT",
	INVALID_PLAYERS: "INVALID_PLAYERS",
	INVALID_DEALER: "INVALID_DEALER",
	INVALID_CONFIGURATION: "INVALID_CONFIGURATION",

	// game state / phase
	INVALID_PHASE: "INVALID_PHASE",
	GAME_FULL: "GAME_FULL",
	GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
	GAME_ALREADY_FINISHED: "GAME_ALREADY_FINISHED",

	// players
	PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
	NOT_PLAYER_TURN: "NOT_PLAYER_TURN",

	// stack
	STACK_NOT_FOUND: "STACK_NOT_FOUND",

	// cards
	CARD_NOT_OWNED: "CARD_NOT_OWNED",
	MUST_FOLLOW_SUIT: "MUST_FOLLOW_SUIT",
	INVALID_CARD: "INVALID_CARD",
	INVALID_DECK: "INVALID_DECK",

	// turup
	INVALID_TURUP_DECLARATION: "INVALID_TURUP_DECLARATION",

	// ghopte
	INVALID_GHOPTE_SUBMISSION: "INVALID_GHOPTE_SUBMISSION",

	// dmn
	INVALID_DMN: "INVALID_DMN",

	// serializers
	INVALID_SERIALIZATION: "INVALID_SERIALIZATION",

	// generic
	INVALID_ACTION: "INVALID_ACTION",
} as const;
